<?php

use GrahamCampbell\Markdown\MarkdownServiceProvider;

// This file is automatically generated by Laravel...

return [
    App\Providers\AppServiceProvider::class,
    App\Providers\FolioServiceProvider::class,
    MarkdownServiceProvider::class,
];
